# azure-pipelines.yml

trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build project'

- task: CopyFiles@2
  inputs:
    contents: '_next/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build output to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish build artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '413ee6c1-ee0d-414f-a5bc-d421aa323bcb'
    appName: 'JSO-Portfolio'
    package: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Deploy to Azure Web App'